#!/bin/sh
ssh seconduser@161.35.44.26
echo "logged in"
alias proj="cd nginx_task"
echo "inside nginx_task"
git pull origin main
echo "just pulled from github"
npm install 
echo "installing dependencies"
npm test || exit 0
echo "all tests passed..."
npm run build
echo "done building project"